### PR TITLE
Create nvd123stools.md

### PR DESCRIPTION
**Pull request by WatchGamingVideos**
Can you help me create more links by deploying my repo here:
https://GitHub.com/interstellarforker/nvd123ishim

My Vercel links stopped working

### CODE REVIEW

**Comment by WatchGamingVideos** [comment]
damn how many checks lol

**Comment by S-PScripts** [comment]
ok

**Comment by WatchGamingVideos** [comment]
also if u do make links give them to me

**Comment by S-PScripts** [comment]
Did you do something to the code? Making a new vercel got the same error: https://nvd123ishim.vercel.app/

**Comment by WatchGamingVideos** [comment]
> Did you do something to the code? Making a new vercel got the same error: https://nvd123ishim.vercel.app/

For some reason Vercel isn't supported anymore lol. I couldn't get my Vercel's to work either its odd

**Comment by WatchGamingVideos** [comment]
My Koyeb link works just fine lol. There are also other services u could probably use

**Comment by S-PScripts** [comment]
you need a credit card for koyeb

netlify has the same error and i got suspended from render

**Comment by WatchGamingVideos** [comment]
wait a sec.

Try Glitch or Pages.Dev

**Comment by WatchGamingVideos** [comment]
Also I couldn't figure out FreeDNS but if you can than that.

Also are you in school? I am

And do you make all the PR0XY links? Just asking.

I think I got banned from Render too for legit no reason I didn't even use it

**Comment by S-PScripts** [comment]
> Also I couldn't figure out FreeDNS but if you can than that.
> 
> Also are you in school? I am
> 
> And do you make all the PR0XY links? Just asking.
> 
> I think I got banned from Render too for legit no reason I didn't even use it

free DNS requires the IP address
I'm on my half term break but i start school next week

i don't have proxies anymore since almost all the websites' owners hate people that have paid proxy links public because the links get banned easily and money is wasted. the owners try dmcaing and taking down people that leak the paid proxy links

**Comment by WatchGamingVideos** [comment]
How's glitch and pages.dev doing?

Also make link names unique but I'm scared if they have these things because my school will flag me and I got flagged like 2 weeks ago:

Cursewords
rizz
suck
ass

Make it family-friendly, I tend to make some links sports or TV related like ronaldo-farm (because he's farming in Saudi League) or homer-simpson (self-explainitory) 

I also like links that are just random like maybe cookie-truck-crushers

U can disregard all of this I don't really care but I can't use it if it has anything slightly bad lol

**Comment by WatchGamingVideos** [comment]
Wait what nation are you in to where you have a break this late into the school year lol

**Comment by S-PScripts** [comment]
> Wait what nation are you in to where you have a break this late into the school year lol

the UK.

next week i have school until July 19th

**Comment by WatchGamingVideos** [comment]
I have 10 mi until my classes begin again then I'm done for pretty much the day

**Comment by S-PScripts** [comment]
> Author

i don't really care about football but i guess manchester city and arsenal are good

**Comment by S-PScripts** [comment]
i couldn't host it on glitch, it auto suspended the project

**Comment by WatchGamingVideos** [comment]
> i couldn't host it on glitch, it auto suspended the project

pages.dev?

**Comment by S-PScripts** [comment]
> > i couldn't host it on glitch, it auto suspended the project
> 
> pages.dev?

paid since cloudflare

**Comment by WatchGamingVideos** [comment]
Bro are there any other services?

**Comment by S-PScripts** [comment]
> Bro are there any other services?

no :(
does github pages work

**Comment by WatchGamingVideos** [comment]
> Re

I think there's Heroku but u could try GitHub Pages

**Comment by S-PScripts** [comment]
> I think there's Heroku but u could try GitHub Pages
koyeb might be  working for you if it hasn't updated to the latest version of your repo

**Pull request merged**
